[gcloud]
disabled = true

[git_status]
# without $stashed
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'

[hostname]
ssh_only = true

[status]
disabled = false

[time]
disabled = false
